# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gibbs sampler in Cpp
#' @keywords internal
gibbs_multivariate_nuisance_cpp <- function(mpg_avg, f_param_avg_half, d, Nb, FZ, eps_r, eps_Z, eps_U, k_0, r_0, Z_0, U_phi_0, phi_def, eta, omega, Sigma, Ntotal, print_interval, numerical_thresh, verbose, L, k_theta, dbList, corrected) {
    .Call(`_vnpc_avg_gibbs_multivariate_nuisance_cpp`, mpg_avg, f_param_avg_half, d, Nb, FZ, eps_r, eps_Z, eps_U, k_0, r_0, Z_0, U_phi_0, phi_def, eta, omega, Sigma, Ntotal, print_interval, numerical_thresh, verbose, L, k_theta, dbList, corrected)
}

#' Store imaginary parts above and real parts below the diagonal
#' @keywords internal
realValuedPsd <- function(f_) {
    .Call(`_vnpc_avg_realValuedPsd`, f_)
}

#' Inverse function to realValuedPsd
#' @keywords internal
complexValuedPsd <- function(f_) {
    .Call(`_vnpc_avg_complexValuedPsd`, f_)
}

#' The log Whittle likelihood for the averaged periodogram
#' @keywords internal
llike_whittle_avg <- function(mpg_avg, f, Nb) {
    .Call(`_vnpc_avg_llike_whittle_avg`, mpg_avg, f, Nb)
}

#' Construct psd mixture
#' @keywords internal
get_f_matrix <- function(U_phi, r, Z, k, dbList) {
    .Call(`_vnpc_avg_get_f_matrix`, U_phi, r, Z, k, dbList)
}

#' Build the correction matrix in the frequency domain based on the q-parametrization with the Cholesky decomposition
#' @keywords internal
get_CFZ_q <- function(FZ, q, f_param_half) {
    .Call(`_vnpc_avg_get_CFZ_q`, FZ, q, f_param_half)
}

#' Build the correction matrix in the frequency domain based on the q-parametrization with square root of matrices
#' @keywords internal
get_CFZ_q_sq <- function(FZ, q, f_param_half) {
    .Call(`_vnpc_avg_get_CFZ_q_sq`, FZ, q, f_param_half)
}

#' Cholesky docomposition representation of a matrix array. See Remark 5.2
#' @keywords internal
chol_cube <- function(f_, excludeBoundary) {
    .Call(`_vnpc_avg_chol_cube`, f_, excludeBoundary)
}

#' Square root of a matrix array. See Remark 5.2
#' @keywords internal
sqrt_cube <- function(f_, excludeBoundary) {
    .Call(`_vnpc_avg_sqrt_cube`, f_, excludeBoundary)
}

#' Log likelihood of a pseudo parametric VAR model
#' @keywords internal
llike_corrected_avg <- function(mpg_avg, f, f_param_avg_half, Nb) {
    .Call(`_vnpc_avg_llike_corrected_avg`, mpg_avg, f, f_param_avg_half, Nb)
}

#' Sum of log determinants of a matrix array excluding boundaries
#' @keywords internal
logdet_cube_sum <- function(f) {
    .Call(`_vnpc_avg_logdet_cube_sum`, f)
}

#' I/O: Only used within Rcpp
#' 
#' This workaround for parsing cubes was neccessary at development time
#' because there was a (presumable) bug in RcppArmadillo that sometimes
#' caused the parsing of arma::cx_cube objects to fail, such that the function
#' received an un-initialized object instead of the parsed one.
#' 
#' The workaround parses an Rcpp vector instead, and manually
#' copies the data in an arma::cx_cube object.
#' Besides being redundant, it also makes the code less readable and it is
#' hoped that this workaround can be removed in future revisions.
#' 
#' @keywords internal
cx_cube_from_ComplexVector <- function(x) {
    .Call(`_vnpc_avg_cx_cube_from_ComplexVector`, x)
}

#' I/O: Only used within Rcpp
#' Note: Same workaround as \code{cx_cube_from_ComplexVector}
#' @keywords internal
cube_from_NumericVector <- function(x) {
    .Call(`_vnpc_avg_cube_from_NumericVector`, x)
}

#' Does a matrix have an eigenvalue smaller than 0?
#' @keywords internal
hasEigenValueSmallerZero <- function(A, TOL = 0.0) {
    .Call(`_vnpc_avg_hasEigenValueSmallerZero`, A, TOL)
}

#' Build an n times n Toeplitz matrix from the 
#' autocovariance values gamma(0),...,gamma(n-1)
#' @keywords internal
acvMatrix <- function(acv) {
    .Call(`_vnpc_avg_acvMatrix`, acv)
}

#' Build an nd times nd Block Toeplitz matrix from the
#' (d times d) autocovariances gamma(0),...,gamma(n-1)
#' @keywords internal
acvBlockMatrix <- function(acv) {
    .Call(`_vnpc_avg_acvBlockMatrix`, acv)
}

#' Computing acceptance rate based on trace
#' Note: Only use for traces from continous distributions!
#' @keywords internal
acceptanceRate <- function(trace) {
    .Call(`_vnpc_avg_acceptanceRate`, trace)
}

#' Hermitian conjugate of a matrix array
#' @keywords internal
trans_cube <- function(f_) {
    .Call(`_vnpc_avg_trans_cube`, f_)
}

#' Matrix products of a matrix array
#' @keywords internal
mult_cube <- function(a_, b_) {
    .Call(`_vnpc_avg_mult_cube`, a_, b_)
}

#' Get U from phi, vectorized, cpp internal only
#' @keywords internal
get_U_cpp <- function(u_phi) {
    .Call(`_vnpc_avg_get_U_cpp`, u_phi)
}

#' Get x from phi, see (62) in Mittelbach et al.
#' @keywords internal
unit_trace_x_from_phi <- function(phi) {
    .Call(`_vnpc_avg_unit_trace_x_from_phi`, phi)
}

#' Get L (lower triangular Cholesky) from x
#' Called U^* in Mittelbach et al, see (60) there
#' @keywords internal
unit_trace_L_from_x <- function(x) {
    .Call(`_vnpc_avg_unit_trace_L_from_x`, x)
}

#' Get p vector, see (67) in Mittelbach et al.
#' @keywords internal
unit_trace_p <- function(d) {
    .Call(`_vnpc_avg_unit_trace_p`, d)
}

#' Get q vector, see (68) in Mittelbach et al.
#' @keywords internal
unit_trace_q <- function(d) {
    .Call(`_vnpc_avg_unit_trace_q`, d)
}

#' Get VARMA PSD from transfer polynomials 
#' Helping function for \code{psd_varma}
#' @keywords internal
varma_transfer2psd <- function(transfer_ar_, transfer_ma_, sigma) {
    .Call(`_vnpc_avg_varma_transfer2psd`, transfer_ar_, transfer_ma_, sigma)
}

#' Get VARMA PSD from transfer polynomials 
#' Helping function for \code{psd_varma_cpp}
#' @keywords internal
varma_transfer2psd_cpp <- function(transfer_ar, transfer_ma, sigma) {
    .Call(`_vnpc_avg_varma_transfer2psd_cpp`, transfer_ar, transfer_ma, sigma)
}

#' VARMA transfer polynomials
#' @keywords internal
transfer_polynomial <- function(lambda, coef) {
    .Call(`_vnpc_avg_transfer_polynomial`, lambda, coef)
}

#' epsilon process (residuals) of VAR model
#' @keywords internal
epsilon_var <- function(zt, ar) {
    .Call(`_vnpc_avg_epsilon_var`, zt, ar)
}

#' sum of multivariate normal log densities
#' with mean 0 and covariance Sigma, unnormalized
#' @keywords internal
sldmvnorm <- function(z_t, Sigma) {
    .Call(`_vnpc_avg_sldmvnorm`, z_t, Sigma)
}

